version: 2

project_name: brag

before:
  hooks:
    - go mod tidy

builds:
  - id: brag
    main: ./main.go
    binary: brag
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/eduardohitek/brag/cmd.Version={{.Version}}

archives:
  - id: brag
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: eduardohitek
    name: brag-cli
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

brews:
  - name: brag-cli
    repository:
      owner: eduardohitek
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}" # <- aqui
    homepage: "https://github.com/eduardohitek/brag-cli"
    description: "Track engineering accomplishments for performance reviews"
    install: |
      bin.install "brag"
    test: |
      system "#{bin}/brag --version"
